server:
  # 端口
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_simple?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  root: INFO
  level:
    tk.fishfish: DEBUG